export const malayalamKeyMap: Record<string, { normal: string, shift: string }> = {
  'KeyQ': { normal: 'ൗ', shift: 'ഔ' }, 
  'KeyW': { normal: 'ൈ', shift: 'ഐ' }, 
  'KeyE': { normal: 'ാ', shift: 'ആ' }, 
  'KeyR': { normal: 'ീ', shift: 'ഈ' }, 
  'KeyT': { normal: 'ൂ', shift: 'ഊ' }, 
  'KeyY': { normal: 'ബ', shift: 'ഭ' }, 
  'KeyU': { normal: 'ഹ', shift: 'ങ' }, 
  'KeyI': { normal: 'ഗ', shift: 'ഘ' }, 
  'KeyO': { normal: 'ദ', shift: 'ധ' }, 
  'KeyP': { normal: 'ജ', shift: 'ഝ' },
  'KeyA': { normal: 'ോ', shift: 'ഓ' }, 
  'KeyS': { normal: 'േ', shift: 'ഏ' }, 
  'KeyD': { normal: '്', shift: 'അ' }, 
  'KeyF': { normal: 'ി', shift: 'ഇ' }, 
  'KeyG': { normal: 'ു', shift: 'ഉ' }, 
  'KeyH': { normal: 'പ', shift: 'ഫ' }, 
  'KeyJ': { normal: 'ര', shift: 'റ' }, 
  'KeyK': { normal: 'ക', shift: 'ഖ' }, 
  'KeyL': { normal: 'ത', shift: 'ഥ' },
  'KeyZ': { normal: 'െ', shift: 'എ' }, 
  'KeyX': { normal: 'ം', shift: 'ഃ' }, 
  'KeyC': { normal: 'മ', shift: 'ണ' }, 
  'KeyV': { normal: 'ന', shift: 'ൻ' }, 
  'KeyB': { normal: 'വ', shift: 'ഴ' }, 
  'KeyN': { normal: 'ല', shift: 'ള' }, 
  'KeyM': { normal: 'സ', shift: 'ശ' },
  'Space': { normal: ' ', shift: ' ' },
  'Comma': { normal: ',', shift: '<' },
  'Period': { normal: '.', shift: '>' },
  'Slash': { normal: '/', shift: '?' },
  'Quote': { normal: "'", shift: '"' },
  'Minus': { normal: '-', shift: '_' },
  'Equal': { normal: '=', shift: '+' },
  'BracketLeft': { normal: '[', shift: '{' },
  'BracketRight': { normal: ']', shift: '}' },
  'Semicolon': { normal: ';', shift: ':' },
};
